name:                wakame
version:             0.1.0.0
github:              "kayhide/wakame"
license:             BSD3
author:              "Hideaki Kawai"
maintainer:          "kayhide@gmail.com"
copyright:           "2020 Hideaki Kawai"
synopsis:            Functions to manipulate records
category:            Data, Records, Generics

extra-source-files:
- README.md
- ChangeLog.md


description:         Please see the README on GitHub at <https://github.com/kayhide/wakame>

dependencies:
- base >= 4.7 && < 5

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedLists
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

library:
  source-dirs: src

tests:
  wakame-doctest:
    main:                Main.hs
    source-dirs:         test/doctest
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - wakame
