name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: ${{ matrix.os }} / stack / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          # - windows-latest
        stack: ["2.1.3"]
        ghc: # set by the resolver
          # - "8.6.5"
          - "8.8.3"
          # - "8.10.1"

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1.1
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - name: Get Stack Root
      id: stack-root
      run: |
          stack path --stack-root --system-ghc
          echo "::set-output name=dir::$(stack path --stack-root --system-ghc)"

    - uses: actions/cache@v1
      name: Cache stack-root
      with:
        path: ${{ steps.stack-root.outputs.dir }}
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc
